/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { DetectionLogFindManyArgs } from "../../detectionLog/base/DetectionLogFindManyArgs";
import { DetectionLog } from "../../detectionLog/base/DetectionLog";
import { DetectionLogWhereUniqueInput } from "../../detectionLog/base/DetectionLogWhereUniqueInput";
import { AudioSampleFindManyArgs } from "../../audioSample/base/AudioSampleFindManyArgs";
import { AudioSample } from "../../audioSample/base/AudioSample";
import { AudioSampleWhereUniqueInput } from "../../audioSample/base/AudioSampleWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          username: true,
          email: true,
          roles: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          username: true,
          email: true,
          roles: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/detectionLogs")
  @ApiNestedQuery(DetectionLogFindManyArgs)
  async findDetectionLogs(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<DetectionLog[]> {
    const query = plainToClass(DetectionLogFindManyArgs, request.query);
    const results = await this.service.findDetectionLogs(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        detectedMusic: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/detectionLogs")
  async connectDetectionLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: DetectionLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      detectionLogs: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/detectionLogs")
  async updateDetectionLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: DetectionLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      detectionLogs: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/detectionLogs")
  async disconnectDetectionLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: DetectionLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      detectionLogs: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/audioSamples")
  @ApiNestedQuery(AudioSampleFindManyArgs)
  async findAudioSamples(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AudioSample[]> {
    const query = plainToClass(AudioSampleFindManyArgs, request.query);
    const results = await this.service.findAudioSamples(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        filePath: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/audioSamples")
  async connectAudioSamples(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AudioSampleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      audioSamples: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/audioSamples")
  async updateAudioSamples(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AudioSampleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      audioSamples: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/audioSamples")
  async disconnectAudioSamples(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AudioSampleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      audioSamples: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
